### PR TITLE
i swear if this isnt merge worthy idk what is

### PR DESCRIPTION
**Pull request by andybrwr**
[am i cool yet](https://alinuxlover.github.io/free-vbucks-fake.github.io)

### CODE REVIEW

**Review by ajayyy — APPROVED** [review]

**Comment by chexbox** [comment]
Merge. it.

**Review by chexbox — APPROVED** [review]
Merge it.

**Comment by andybrwr** [comment]
^^^

**Comment by DeleteThisAcount** [comment]
i want to see if it works

**Comment by DeleteThisAcount** [comment]
idk what does

**Comment by ajayyy** [comment]
merge it anyway

**Comment by DeleteThisAcount** [comment]
> merge it anyway

but what it do

**Comment by DeleteThisAcount** [comment]
why isnt this the main index.html, this is legendary

**Comment by ajayyy** [comment]
I don't know how I found this repository

**Comment by DeleteThisAcount** [comment]
same

**Pull request merged**
